/*
Copyright © 2024 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery"
	"github.com/DrBushytop/amag/pkg/kql"
	"github.com/charmbracelet/log"
	"golang.org/x/net/context"
	"regexp"
	"time"

	"github.com/spf13/cobra"
)

var metricCmd = &cobra.Command{
	Use:   "metric",
	Short: "Run a KQL query and save the result as a custom Azure Monitor metric",
	Long: `Run a specified KQL file against an Azure Log Analytics workspace, aggregate the result,
and save it as a custom metric in Azure Monitor. This command is useful for transforming
Log Analytics query results into metrics that can be monitored and visualized over time.

Example usage:

amag aggregate metric --file /path/to/query.kql --metric LatencyP90 --workspaceid <workspace-id> --scoperesourceid <scope-resource-id>

This command requires:
- A KQL query file that defines the aggregation.
- A valid workspace ID where the query will be executed.
- A scope resource ID where the custom metric will be saved. This can be a resource or subresource ID.`,
	Run: RunAggregateMetric,
}

func RunAggregateMetric(cmd *cobra.Command, args []string) {
	metricName, _ := cmd.Flags().GetString("metric")
	fileName, _ := cmd.Flags().GetString("file")
	workspaceId, _ := cmd.Flags().GetString("workspaceid")
	scopeResourceId, _ := cmd.Flags().GetString("scoperesourceid")
	if err := validateResourceId(scopeResourceId); err != nil {
		log.Error("Error validating scopeResourceId", "err", err)
		return
	}

	cmd.SilenceUsage = true // Avoid printing usage on error generated by functions later

	aggregate, err := kql.ParseQuery(fileName)
	if err != nil {
		log.Error("Error parsing aggregate", "err", err)
		return
	}

	log.Infof("Running Query:\n%s", aggregate)

	wsClient, err := kql.NewWorkspaceClient(workspaceId)
	if err != nil {
		log.Error("Failed to create workspace client", "err", err)
		return
	}

	res, err := wsClient.QueryWorkspaceForAggregateValue(
		context.Background(),
		azquery.Body{
			Query:    to.Ptr(aggregate),
			Timespan: to.Ptr(azquery.NewTimeInterval(time.Now().Add(time.Duration(-24)*time.Hour), time.Now())),
		},
		nil,
	)
	if err != nil {
		log.Error("Failed to aggregate workspace", "err", err)
		return
	}

	body := kql.NewCustomMetricsBody(metricName, res)

	cmClient, err := kql.NewCustomMetricsClient()
	if err != nil {
		log.Error("Failed to create custom metrics client", "err", err)
		return
	}
	log.Info("Sending custom metric")
	if err := cmClient.SendCustomMetrics(context.Background(), scopeResourceId, "westeurope", body); err != nil {
		log.Error("Failed to send custom metrics", "err", err)
	}

	log.Info("Saved custom metric", "metricName", metricName, "metricValue", res, "scope", scopeResourceId)
}

func validateResourceId(resourceId string) error {
	unifiedPattern := `^/subscriptions/([a-f0-9\-]{36})/resourceGroups/([a-zA-Z0-9_\-\.]+)/providers/([a-zA-Z0-9_\-\.]+)/([a-zA-Z0-9_\-\.]+)/([a-zA-Z0-9_\-\.]+)(?:/([a-zA-Z0-9_\-\.]+)/([a-zA-Z0-9_\-\.]+))?$`
	reUnified := regexp.MustCompile(unifiedPattern)

	if !reUnified.MatchString(resourceId) {
		return fmt.Errorf("invalid resourceId format. Metrics only support resource or subresource scope")
	}
	return nil
}

func init() {
	aggregateCmd.AddCommand(metricCmd)

	metricCmd.Flags().StringP("file", "f", "", "Relative path to a KQL file to run")
	_ = metricCmd.MarkFlagRequired("file")
	metricCmd.Flags().StringP("metric", "m", "", "Name of the custom metric to save the result into")
	_ = metricCmd.MarkFlagRequired("metric")
	metricCmd.Flags().StringP("workspaceid", "w", "", "Workspace id (not the resource id) of the Log Analytics workspace to run the aggregate against")
	_ = metricCmd.MarkFlagRequired("workspaceid")
	metricCmd.Flags().StringP("scoperesourceid", "s", "", "Resource id of the scope to save the custom metric to")
	_ = metricCmd.MarkFlagRequired("scoperesourceid")
}